<a href="https://colab.research.google.com/github/AshishKhadka1/Machine-Learning/blob/main/3_1_Complete_Numpy_tutorial_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy - Numerical methods**

Advantages of Numpy Arrays:
1. Allows several Mathematical Operations
2. Faster Operations

In [5]:
import numpy as np

#List VS NumPy - Time taken

In [1]:
from time import process_time

Time taken by a List

In [3]:
python_list = [i for i in range (10000)]    # create list like : 0, 1, 2, 3 ...., 9999

start_time = process_time()                 # Record CPU time before running the operation

python_list = [i + 5 for i in python_list]  # new list becomes : 5, 6, 7, ...., 10004

end_time = process_time()

print(end_time - start_time)

0.0008824629999999445


Time Taken by Numpy

In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5               # np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.00043642400000010184


NumPy Arrays

In [7]:
# List
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
# Creating a 1 dimensional array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [10]:
a.shape

(5,)

In [16]:
# creating a 2 dimensional Arrray
b = np.array([(1, 2, 3, 4, 5), (0, 1, 2, 3, 4)], dtype = float)
print(b)

[[1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4.]]


In [15]:
b.shape

(2, 5)

Initial Placeholders in numpy array

In [18]:
# Create a numpy array of Zeros
x = np.zeros((4,5))
#Create a numpy of Ones
y = np.ones((2,3))
print(y)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
# array of particular value
z= np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
# create an Identity matrix
a = np.eye((4))
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# Create a numpy array with Random Values
b = np.random.random((3,4))
print(b)


[[0.72863029 0.38139448 0.14753039 0.106275  ]
 [0.32221474 0.92295017 0.97816411 0.80860914]
 [0.69871134 0.17023008 0.7379702  0.07089655]]


In [22]:
# random integer values array within specific range
c = np.random.randint(10,100,(3,4))
print (c)

[[28 98 92 72]
 [24 57 97 83]
 [73 93 39 24]]


In [24]:
# array of evenly spaced values ---> Number of values we want
d = np.linspace(10,20,3)     # how many value we want
print(d)

[10. 15. 20.]


In [26]:
 # array of evenly spaced values ---> specifying the step
e = np.arange(10,30,5)      # 5 units
print(e)

[10 15 20 25]


In [27]:
# Convert a list to a NumpyArray
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)

print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a NumPy array

In [28]:
c = np.random.randint(10,90,(5,5))
print(c)

[[10 30 82 29 10]
 [19 43 76 78 74]
 [16 15 40 12 10]
 [52 36 77 63 45]
 [11 39 86 64 84]]


In [29]:
# array dimension
print(c.shape)        # Rows and Column

(5, 5)


In [30]:
# Number of dimesions
print(c.ndim)         #two dimension as : Rows and Column

2


In [31]:
# Number of elements in an array
print(c.size)

25


In [32]:
# Checking data type of values in the array
print(c.dtype)

int64


#**Mathematical Operations in np array**


In [33]:
list1 = [1, 2, 3, 4, 5]
list2 = [2, 1, 5, 8, 9]

print(list1 + list2)          # '+' concatenate or join two lists

In [36]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 5 3]
 [1 9 6]
 [6 9 4]]
[[14 15 14]
 [19 15 16]
 [15 10 11]]


In [38]:
print (a+b)   # Element wise addition
print (a-b)
print (a*b)
print (a/b)

[[17 20 17]
 [20 24 22]
 [21 19 15]]
[[-11 -10 -11]
 [-18  -6 -10]
 [ -9  -1  -7]]
[[ 42  75  42]
 [ 19 135  96]
 [ 90  90  44]]
[[0.21428571 0.33333333 0.21428571]
 [0.05263158 0.6        0.375     ]
 [0.4        0.9        0.36363636]]


In [41]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a, b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[4 8 2]
 [0 9 7]
 [4 6 5]]
[[19 11 10]
 [19 15 15]
 [19 13 14]]
[[23 19 12]
 [19 24 22]
 [23 19 19]]
[[-15  -3  -8]
 [-19  -6  -8]
 [-15  -7  -9]]
[[ 76  88  20]
 [  0 135 105]
 [ 76  78  70]]
[[0.21052632 0.72727273 0.2       ]
 [0.         0.6        0.46666667]
 [0.21052632 0.46153846 0.35714286]]


#**Array Manipulation**


In [42]:
array = np.random.randint(0, 10,(2, 3))
print(array)
print(array.shape)

[[8 6 5]
 [3 1 5]]
(2, 3)


In [44]:
# Tanspose
trans = np.transpose(array)    # Transpose of matrix
print(trans)
print(trans.shape)

[[8 3]
 [6 1]
 [5 5]]
(3, 2)


In [45]:
array = np.random.randint(0, 10,(2, 3))
print(array)
print(array.shape)

[[0 6 3]
 [9 9 1]]
(2, 3)


In [46]:
trans2 = array.T      # Transpose of matrix new way
print(trans2)
print(trans2.shape)

[[0 9]
 [6 9]
 [3 1]]
(3, 2)


In [47]:
# reshaping a array

a= np.random.randint(0,10,(2,3))

print(a)
print(a.shape)

[[4 0 0]
 [2 8 7]]
(2, 3)


In [51]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 0]
 [0 2]
 [8 7]]
(3, 2)
